name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install --immutable
    - run: yarn tsc
    - run: yarn build
    - name: Setup .yarnrc.yml file to allow publication to https://registry.npmjs.org with a 'yarn npm publish'
      shell: bash
      run: |
        echo "npmAuthToken: ${{ secrets.NPM_TOKEN }}" >> ~/.yarnrc.yml
    - run: yarn npm publish
